### PR TITLE
Added ability to switch labels and values in makeSelects

### PR DESCRIPTION
**Pull request by bretto36**
Added ability to switch labels and values in makeSelects and automatically in relationships as the value should be unique, the label can be duplicated

### CODE REVIEW

**Comment by mlantz** [comment]
Why do you force the switch on the relationship? Do you have an example?

**Comment by bretto36** [comment]
I figured the value field would always be unique considering it defaults to id. I like the idea of showing duplicate labels as it shows people that there are duplicates and they can fix the data. I've had issues where people named a page the same thing but it was 2 separate pages. In the list of drop downs it only shows 1 and they can never select it.

**Comment by mlantz** [comment]
I would be ok having the switch option - but I don't want it forced on the relationships. I think there should be control on data, but I could see the ability to switch things being useful. So if you remove the force one on the relationships then I'm cool with it. Especially since with the relationships you can set the fields that are displayed. Maybe it would be even better if you could set the 'label' and 'value' for the selects that would be the best solution probably.

**Comment by bretto36** [comment]
Maybe it would be even better if you could set the 'label' and 'value' for the selects that would be the best solution probably. 
Can you explain this more please? I'm not sure what you mean.

**Comment by mlantz** [comment]
Right now with relationships you can tell the config, which column should be the value, and which should be the label in the select menu it generates. I thought the same config could be done in the select maker that way, you can manually set whichever you want but by default it will use id and name :)

**Comment by mlantz** [comment]
Upon further review. I don't think this is a real problem. The system works on a key => value. Which means it can be any key, value a person wants. The idea of adding a switch mechanism, means that though they are giving the input maker an array of key value pairs they want the input maker to switch the keys and values. As I see it you can easily do this to your data directly. 

In terms of relationships, and making those selects the config allows you to chose which column will act as the label, and which will act as the value for the options. Thanks for the energy, but I think its better to give it the data that will be represented rather than having it intake data and do flips and switches. Thanks.

**Pull request closed without merging**
