### PR TITLE
fix db transaction and ModelFactory Create

### PR DESCRIPTION
**Pull request by Ray-Cheng**

### CODE REVIEW

**Comment by Ray-Cheng** [comment]
@mlantz should be ok now?

**Comment by mlantz** [comment]
I strongly disagree with having the transactions removed from the try catch. The transaction and commit only occurs within the try, so with the catch doing a rollback what is it rolling back? As I see it there has not been a db action to rollback. I'd be ok with the content of the try being wrapped inside a `DB::transaction(function(){ //content in here });` but thats about as far as I would go. These are 'templates' for an app structure so I would encourage people to mod them as they need within their own apps. Please remove those and put in a new PR for the transactions if you want. Thanks.

**Comment by Ray-Cheng** [comment]
@mlantz I found these problem when i invite a person and email not configured correctly,Actually i think transaction should start before user created,code like this:

    public function invite($info)
    {
        $password = substr(md5(rand(1111, 9999)), 0, 10);

        DB::beginTransaction();
        try {
              $user = $this->userRepo->create([
                  'email' => $info['email'],
                  'name' => $info['name'],
                  'password' => bcrypt($password)
              ]);
              $this->create($user, $password, $info['roles'], true);
                DB::commit();
            } catch (Exception $e) {
                DB::rollBack();
                throw new Exception("We were unable to generate your profile, please try again later.", 1);
          }
          return $user;
       }

if not doing this,when email send fail the new user already created in db.
and can you tell me why DB::rollBack() can't write in catch block? in my opinion, when start a db transaction, database will lock related tables , after excute DB::commit() or DB::rollBack() release this lock, and it doesn't matter how php code write.Any Exceptions occur in try block  we rollback what db have changed seems won't have a problem.

**Comment by mlantz** [comment]
I'd rather just have them wrapped in the DB::transaction closure. Its much easier to read that way and achieves the same thing. I didnt really think it through on first review, but you're right the rollback would just open up the lock. In the end I dont like how it reads. I mostly dont like the idea of the DB::beginTransaction being outside of the try catch. I'd much rather have it all bundled together with the closure. This should also be a separate PR since its addressing another issue.

**Comment by Ray-Cheng** [comment]
@mlantz , in this place if we want use `DB:: transaction`, must change some logic, because except databases operations ,there have a email send function.when email can not send,should rollback too or give different notice message.so it's better let yourself modify this part.

**Comment by mlantz** [comment]
Hey @Ray-Cheng I just went ahead and changed it. but I'd like to get your other fix in. I appreciate how much energy you've put into our chats. Can you drop your transactions, so we can merge in the rest? I haven't done a new release yet but I will be soon.

**Comment by Ray-Cheng** [comment]
@mlantz ,rolled back commits related db transaction

**Pull request merged**
