### PR TITLE
PureCSS framework

### PR DESCRIPTION
**Pull request by absalomedia**
Yahoo's PureCSS as a view/css framework.

- Custom Pure 0.6.0 build with 7ths, Grids & Normalizer
- Form creator overloading so it negotiates Bootstrap & Pure
- Responsive sidebar menu
- ARIA roles
- New Google Fonts, with font weighting & balance

### CODE REVIEW

**Comment by absalomedia** [comment]
Closing while I patch team admin layout

**Comment by mlantz** [comment]
I'm concerned that PureCSS has had very few commits in the past year. Is it maintained on a regular basis? Though I'm really impressed with how much effort you've put in, this may be better suited as a custom package. I'd rather do some revamping of how the CRUD sets a UI before I add support for another one. Have it do something like `--ui=bootstrap|semantic|plain`. Do you use PureCSS quite often?

**Comment by absalomedia** [comment]
There were some initial pushes to get it to 0.6 early in the year before Yahoo went a bit quiet. There's now some project handover going on &  it looks tol be ramping back up to into regular maintenance / development, to resolve all the outstanding PR & issues very soon as seen [here](https://github.com/yahoo/pure/issues/557)

So active development & regular usage of the core PureCSS package, even if things aren't fully back up to release cycles yet (hopefully next month on that for the official package?).

I do use PureCSS quite a lot. I tend to find it makes thing run faster as it doesn't have the overhead of the combined Bootstrap CSS/JS mix.

**Comment by mlantz** [comment]
Sounds fair, I'm still concerned about the fact that its not even in a version 1.0 yet. I would still suggest creating your own package and releasing it as a UI for Laracogs starter kit. I'd be happy to put up a community section on the site and promote it. At Yab we mostly use Bootstrap so supporting a bunch of UI kits is not really in our purview. Even our support for Semantic UI (2.2) is quite limited, and I have no guarantee we will do that for a very long time. If you feel it helps you speed up development, and can help others I'm more than happy to promote it, but like I said its not within our scope to offer support for this UI if it was added to the package, ensuring that it worked with the latest stable versions of PureCSS. 

Thanks again for the work you put in, and please let me know if you'd like us to put up a link on the site, promoting a package if you chose to make one.

**Comment by absalomedia** [comment]
There's a few questions I need answered to help move this forward:

1. There seems little documentation apart from 1 starter kit on Packalyst regarding how to UI theme the starter. Do you have any?
2. The FormMaker patch I've done in order to make Laracogs play well with non Bootstrap related themes is outside the scope of a starter kit. What do you suggest here?

I've notice the FormMaker / InputMaker utilities don't have a clear separation between login & presentation yet. If they were aimed at rendering agnostic views inside the starter kits as part of such a seperation this might help.

**Comment by mlantz** [comment]
Hey so to answer your questions:

1. Nope no docs on that. You kinda have to map it as you see fit. I generally set a test env and just keep re-running the starter command to test whether the new views work or not. Plain old trail and error.

2. To me the FormMaker patch you put in just adds another class to support another UI not really solving the problem but adding another class for pure. I'd rather have it be refactored to use 'form-control' by default and then have a custom class override. (I'll do some refactoring for that but good idea)

Not too sure what you mean by separation between login/ and presentation. Not too sure why these would be different. Let me know what you're thinking with this.

**Comment by absalomedia** [comment]
Typo. Was meant to state separation between logic & presentation.

**Comment by mlantz** [comment]
There is a degree of separation in that there is the html generators and general configuring methods to construct the resulting form. If you think they would be better to be broken up further feel free to go for it. I've got other stuff I'm working on for Laracogs currently, so the more improvements the better thanks.

**Pull request closed without merging**
